### ISSUE TITLE
Can you update your 'zip' dependency to 'rubyzip'?

### ISSUE THREAD

**Issue by lmckenzie** [neo4jrb/neo4j-rake_tasks#12]
I would like to use your gem but I am running into a lot of conflicts with the old dependency on 'zip' instead of 'rubyzip'.

**Comment by cheerfulstoic** [comment]
Yeah, I'd be happy to make that switch.  It looks like the main difference is that `zip` supports Ruby 1.9.1 whereas rubyzip requires 1.9.2.  Our requirements for the neo4j.rb gems is 1.9.3 so we should be good there ;)

Let me take a minute and see what's required

**Comment by lmckenzie** [comment]
Thanks! I would really appreciate it.

**Comment by cheerfulstoic** [comment]
Ok, released 0.1.0 of `neo4j-rake_tasks` and 5.1.4 of `neo4j-core` (which just updates the version dependency for `neo4j-rake_tasks`).

Please reopen if that doesn't help!

**Comment by lmckenzie** [comment]
This was perfect! Seriously thanks for responding so quickly!

**Comment by cheerfulstoic** [comment]
Glad to help!
