### ISSUE TITLE
org.neo4j.server.webserver.https.port needs valid value even if .https.enabled=false

### ISSUE THREAD

**Issue by bobmazanec** [neo4jrb/neo4j-rake_tasks#19]
Mac OS X El Capitan (10.11.3)

I cannot get `rake neo4j:start[any_environment]` to succeed...

**Given**
- `neo4j` gem v6.1.6, `neo4j-core` v6.1.2, and `neo4j-rake_tasks` v0.4.1
- **And** `$  rake neo4j:install[community-latest,test]  # => Latest version is: 2.3.2[...]`
- **And** `$  rake neo4j:config[test,7575  # => [...] Config ports 7575 / 7574`)

**When** `$ rake neo4j:start[test]`

**Then**
- it fails:

  ```
Starting Neo4j in test...
Unable to find any JVMs matching version "1.7".
Starting Neo4j Server...WARNING: not changing user
process [91829]... waiting for server to be ready.. Failed to start within 120 seconds.
Neo4j Server may have failed to start, please check the logs.
rake aborted!
Unable to run: db/neo4j/test/bin/neo4j start
/Users/bob/.rvm/gems/ruby-2.2.1@hattr/gems/neo4j-rake_tasks-0.4.1/lib/neo4j/rake_tasks/server_manager.rb:171:in `system_or_fail'
/Users/bob/.rvm/gems/ruby-2.2.1@hattr/gems/neo4j-rake_tasks-0.4.1/lib/neo4j/rake_tasks/server_manager.rb:30:in `start'
/Users/bob/.rvm/gems/ruby-2.2.1@hattr/gems/neo4j-rake_tasks-0.4.1/lib/neo4j/rake_tasks/neo4j_server.rake:54:in `block (2 levels) in <top (required)>'
/Users/bob/.rvm/gems/ruby-2.2.1@hattr/bin/ruby_executable_hooks:15:in `eval'
/Users/bob/.rvm/gems/ruby-2.2.1@hattr/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => neo4j:start
(See full trace by running task with --trace)
```
- **And** `db/neo4j/test/data/log/console.log` suggests a problem with the port #(s):
  ```
2016-02-13 19:38:30.950+0000 ERROR [org.neo4j]: Failed to start Neo Server on port [unknown port] Bad value '-1' for setting 'org.neo4j.server.webserver.https.port': must be a valid port number
org.neo4j.graphdb.config.InvalidSettingException: Bad value '-1' for setting 'org.neo4j.server.webserver.https.port': must be a valid port number
	at org.neo4j.helpers.Settings$DefaultSetting.apply(Settings.java:927)
	at org.neo4j.helpers.Settings$DefaultSetting.apply(Settings.java:847)
	at org.neo4j.kernel.configuration.ConfigurationValidator.validate(ConfigurationValidator.java:50)
	at org.neo4j.kernel.configuration.Config.applyChanges(Config.java:148)
	at org.neo4j.kernel.configuration.Config.registerSettingsClasses(Config.java:104)
	at org.neo4j.server.configuration.PropertyFileConfigurator.setServerSettingsClasses(PropertyFileConfigurator.java:87)
	at org.neo4j.server.configuration.PropertyFileConfigurator.<init>(PropertyFileConfigurator.java:80)
	at org.neo4j.server.Bootstrapper.createConfigurationBuilder(Bootstrapper.java:238)
	at org.neo4j.server.Bootstrapper.start(Bootstrapper.java:107)
	at org.neo4j.server.Bootstrapper.main(Bootstrapper.java:69)
```

- **And** `data/graph.db/` does not exist:
  ```
$ ls -l db/neo4j/test/data/graph.db/
ls: db/neo4j/test/data/graph.db/: No such file or directory
```

**Comment by bobmazanec** [comment]
Hmmm...maybe not...

**Comment by cheerfulstoic** [comment]
Glad that it's working, but in case it isn't in the future you might check out the `data/graph.db/messages.log`.

Honestly, it would be kind of cool if we automatically captured the part of that log that changed during the run of the rake task and automatically outputted it when something fails.  A lot of people don't know about the file.  An easier solution may be to simply tell people the path for the file so that they can tail it.

**Comment by bobmazanec** [comment]
Thanks for the thought/suggestion; I'm still poking and have updated the base issue.

**Comment by bobmazanec** [comment]
I have a feeling I'll be embarrassed at the end of all this, but for posterity...

`db/neo4j/test/conf/neo4j-server.properties` includes...
```
# http port (for all data, administrative, and UI access)
org.neo4j.server.webserver.port=7575

[...]

# Turn https-support on/off
org.neo4j.server.webserver.https.enabled=false

# https port (for all data, administrative, and UI access)
org.neo4j.server.webserver.https.port=-1
```

**Comment by bobmazanec** [comment]
Changing that `-1` to `7676` got me going:
```
Unable to find any JVMs matching version "1.7".
Starting Neo4j Server...WARNING: not changing user
process [92661]... waiting for server to be ready...... OK.
http://localhost:7575/ is ready.
```

and my browser can connect on 7575

Is there an Issue here?
If so, what kind(s) of PR(s) would you want?

**Comment by bobmazanec** [comment]
Maybe it was an earlier gem version or something.

- Deleted `db/neo4j`
- re-ran `rake neo4j:install[community-latest,env]` for both `development` and `test`
- both set...
 - `org.neo4j.server.webserver.https.enabled=true`
 - `org.neo4j.server.webserver.https.port=7473`
- both `start` and `stop` successfully

Thanks for the help; sorry for the churn!

**Comment by cheerfulstoic** [comment]
No problem, I'd definitely that people overreported issues than underreported ;)

**Comment by cheerfulstoic** [comment]
Really weird, I don't know how the `-1` got set...

**Comment by bobmazanec** [comment]
Ah ha &mdash; apparently that's what I needed someone to 'ask!'

`$ rake neo4j:config[development]` sets 0 / -1 &mdash; I did that (several times?) while fumbling about...

reported as #20 rather than flog this one any more :smile:
