### ISSUE TITLE
:config task does not replace https port -1

### ISSUE THREAD

**Issue by bobmazanec** [neo4jrb/neo4j-rake_tasks#20]
`$ rake neo4j:config[env]` sets the http/s ports to 0 / -1 &mdash; _i.e._,

db/neo4j/env/conf/neo4j-server.properties:
```
[...]
org.neo4j.server.webserver.port=0
[...]
org.neo4j.server.webserver.https.port=-1
```

`$ rake neo4j:config[env,7474]`...
 - **claims** to set them to 7474 / 7473
 - **actually** changes only the http port, leaving
```
[...]
org.neo4j.server.webserver.port=7474
[...]
org.neo4j.server.webserver.https.port=-1
```

**Comment by bobmazanec** [comment]
Faulty regex &mdash; `(\w+)` in `Neo4j::RakeTasks::ServerManager#modify_config_file`
doesn't match the `-` in `-1`.

Easy fix: change it to `(-?\w+)` (or maybe you want the regex more general?).

The `StarnixServerManager#config` examples are a little, um, 'sparse' at the moment. :smile:

Better to check the actual saved config value(s) directly?
Is there a good/preferred way to do that?

**Comment by cheerfulstoic** [comment]
Probably would be good to make it more general.  I would say that we could just match any character until the end of the line.

And yeah, the specs could definitely use some work ;)

Probably if we had specs for it we could just have a simple file (or maybe it could be refactored to work on a string) with just the property (or not).  Testing various values should do it.

I think also that `config` should require an argument for the port
