### ISSUE TITLE
neo4j rake tasks matches nothing in zsh shell

### ISSUE THREAD

**Issue by islam-taha** [neo4jrb/neo4j-rake_tasks#22]
while configuring testing port to 7475 with this ```rake neo4j:config[test,7475]``` in zsh shell nothing is run and zsh outputs this error ```zsh: no matches found: neo4j:config[test,7475]```
what is the kind of this issue ?

**Comment by cheerfulstoic** [comment]
I think that this is an issue between `zsh` and `rake`.  Could you try this?

https://robots.thoughtbot.com/how-to-use-arguments-in-a-rake-task

**Comment by islam-taha** [comment]
thank you very much that was a problem with zsh in parsing rake arguments, now i'm passing rake commands in strings like that ```rake 'neo4j:config[test,7475]'```.
That's working

**Comment by cheerfulstoic** [comment]
Awesome! ;)
