### ISSUE TITLE
Travis ci don't work with test

### ISSUE THREAD

**Issue by kunitoo** [neo4jrb/neo4j-rake_tasks#25]
I think it should work together test when Travis ci to work.
However, it run only ./release_if_new.rb. https://github.com/neo4jrb/neo4j-rake_tasks/blob/master/.travis.yml#L1

**Comment by cheerfulstoic** [comment]
Thanks for the issue!  I'm going to be pretty busy until next week, but this is on my list to look at soon

**Comment by cheerfulstoic** [comment]
I think I've got the specs in a pretty reliable state now.  There's not much to them, but they're working (on travis and locally for me).

Let me know if you need help with anything else!
