### ISSUE TITLE
Depends on a version of `rubyzip` that causes deoptimization issues in JRuby

### ISSUE THREAD

**Issue by angryzor** [neo4jrb/neo4j-rake_tasks#26]
See [https://github.com/rubyzip/rubyzip/issues/274](https://github.com/rubyzip/rubyzip/issues/274) and [https://github.com/rubyzip/rubyzip/pull/252](https://github.com/rubyzip/rubyzip/pull/252). This was fixed in version 1.2, but neo4j-rake_tasks forces it at version 1.1.7.

**Comment by cheerfulstoic** [comment]
Just released `neo4j-rake_tasks` v`0.4.4` which should allow you to update your version of rubyzip.

Closing issue, but let me know if that doesn't work!
