### ISSUE TITLE
Gem has runtime dependency that monkey-patches String class

### ISSUE THREAD

**Issue by dominicsayers** [neo4jrb/neo4j-rake_tasks#38]
The `rake` tasks use colorized output (e.g. https://github.com/neo4jrb/neo4j-rake_tasks/blob/master/lib/neo4j/rake_tasks/neo4j_server.rake#L37) which looks cool.

The downside is that this is achieved by including the `colored` gem, which monkey-patches the `String` class to add methods like `cyan`.

Because `neo4j-rake_tasks` is a runtime dependency of `neo4j-core` the monkey-patching flows through into any ruby project that uses Neo4J via `neo4j-core`.

Monkey-patching a Ruby core class is not required to achieve the cool output and it would be better to do this in a more hygienic way that doesn't have potential unintended consequences.

The same effect could be achieved with (for example) the `rainbow` gem without the side-effects.

**Comment by cheerfulstoic** [comment]
This is 100% fair!  I'll make this change shortly.

Separately, though, I would like to remove `neo4j-core`'s dependency on the `neo4j-rake_task` command, because not everybody uses the rake tasks to set up / manage Neo4j servers.

**Comment by cheerfulstoic** [comment]
Released as `0.7.12`, thanks!

**Comment by dominicsayers** [comment]
👍 I was going to submit a PR when I had time, but you beat me to it!
