### ISSUE TITLE
Update README for installation instructions

### ISSUE THREAD

**Issue by pmackay** [neo4jrb/neo4j-rake_tasks#40]
The README says this gem is installed by default with `neo4j` but currently thats not the case. Be good to clarify it needs to be added separately.

Additional information which could be helpful if relevent to your issue:

### Runtime information:

Neo4j database version:
`neo4j` gem version: 9.0.5
`neo4j-core` gem version: 8.0.0

**Comment by cheerfulstoic** [comment]
Good point, thanks!

https://github.com/neo4jrb/neo4j-rake_tasks/commit/a72d3efec902761d61e1ea7f5c255feb6819262c
